//
//  myFs-info.h
//  myFs
//
//  Created by Oliver Waldhorst on 07.09.17.
//  Copyright © 2017 Oliver Waldhorst. All rights reserved.
//

// DO NOT EDIT THIS FILE!!!

#ifndef myFs_info_h
#define myFs_info_h

struct MyFsInfo {
    char *logFile;
    char *contFile;
};

#endif /* myFs_info_h */
